import { API } from "./api";

export const addProducts = async ({
  productDetail,
  vendor_id,
  name,
  brand_id,
  condition_id,
  categories,
  description,
  enabled,
  memberships,
  shipping_to_zones,
  tax_exempt,
  price,
  sale_price_type,
  arrival_date,
  inventory_tracking,
  quantity,
  sku,
  participate_sale,
  sale_price,
  og_tags_type,
  og_tags,
  meta_desc_type,
  meta_description,
  meta_keywords,
  product_page_title,
  facebook_marketing_enabled,
  google_feed_enabled,
  imagesOrder,
  deleted_images,
}) => {
  try {
    const result = await API.post("/apiAdmin/products/create", {
      productDetail,
      vendor_id,
      name,
      brand_id,
      condition_id,
      categories,
      description,
      enabled,
      memberships,
      shipping_to_zones,
      tax_exempt,
      price,
      sale_price_type,
      arrival_date,
      inventory_tracking,
      quantity,
      sku,
      participate_sale,
      sale_price,
      og_tags_type,
      og_tags,
      meta_desc_type,
      meta_description,
      meta_keywords,
      product_page_title,
      facebook_marketing_enabled,
      google_feed_enabled,
      imagesOrder,
      deleted_images,
    });
    return [result.data, null];
  } catch (error) {
    return [null, error];
  }
};
